export const ADJUST_INGREDIENTS = 'ADJUST_INGREDIENTS';
export const SET_INITIAL_INGREDIENTS = 'SET_INITIAL_INGREDIENTS';
export const GET_ORDERS = 'GET_ORDERS';
export const FETCH_INGREDIENTS_ERROR = 'FETCH_INGREDIENTS_ERROR';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
